fix: most of the exceptions
The-Goo-Goo-Gang/nogo-backend pull request #26
Opened 2023-05-09 13:02 UTC by weizihong

2023-05-09 16:02 UTC, andylizf requested changes

2023-05-09 16:02 UTC, andylizf commented on server.hpp
> +                    player = Player { participant, name, role, PlayerType::LOCAL_HUMAN_PLAYER };
Split this huge code blick. You can first determine the player type. like 
```c++
auto player_type { participant->is_local ? PlayereType::LOCAL_HUMAN_PLAYER : PlayerType::REMOTE_HUMAN_PLAYER};
```
And construct the player.
Then, use the try-catch block and enroll the player.
Finally, deliver_to_what based on is_local

2023-05-10 11:34 UTC, weizihong commented on contest.hpp
> +            throw RoleOccupied("Role already occupied");
I don't understand what should I do.

2023-05-10 11:37 UTC, weizihong commented on contest.hpp
> +    class StatusError : public std::logic_error {
Enroll or reject player also use StatusError.

2023-05-10 16:27 UTC, andylizf commented on contest.hpp
> +            result = { -player.role, WinType::SUICIDE };
logger.warn

2023-05-10 16:38 UTC, andylizf commented on server.hpp
> +                logger->error("Concede: Contest stautus is {}", std::to_underlying(contest.status));
BTW, typo. It's `status`

2023-05-10 16:38 UTC, andylizf commented on contest.hpp
> +            throw PlayerExistException("Player already in list");
use {} to construct

2023-05-10 16:40 UTC, andylizf commented on contest.hpp
> +            throw RoleOccupied("Role already occupied");
like `throw RoleOccupiedException{ "Role already occupied" };`

2023-05-13 07:29 UTC, andylizf approved these changes

2023-05-13 07:36 UTC, merged